### ISSUE TITLE
BUG: some path not working on mac with the nightly build of Slicer 07/12/2017

### ISSUE THREAD

**Issue by Punzo** [pieper/CustomSlicerGenerator#12]
Hi @pieper, 

I am creating SlicerAstro custom binaries. On linux worked  perfectly as always, but on mac I have path issues once I try to lunch the new custom binaries (see below). The issue seems to happen only for loadable modules. 

N-145-97-139-226:MacOS vdhulst$ ./SlicerAstro-Beta
  Error(s):
    The file '/Users/vdhulst/Downloads/SlicerAstro-Beta.app/Contents/lib/Slicer-4.9/qt-loadable-modules/libqSlicerAstroModelingModule.dylib' is not a valid Qt plugin.
  Error(s):
    The file '/Users/vdhulst/Downloads/SlicerAstro-Beta.app/Contents/lib/Slicer-4.9/qt-loadable-modules/libqSlicerAstroMomentMapsModule.dylib' is not a valid Qt plugin.
  Error(s):
    The file '/Users/vdhulst/Downloads/SlicerAstro-Beta.app/Contents/lib/Slicer-4.9/qt-loadable-modules/libqSlicerAstroSmoothingModule.dylib' is not a valid Qt plugin.
  Error(s):
    The file '/Users/vdhulst/Downloads/SlicerAstro-Beta.app/Contents/lib/Slicer-4.9/qt-loadable-modules/libqSlicerAstroVolumeModule.dylib' is not a valid Qt plugin.
  Error(s):
    The file '/Users/vdhulst/Downloads/SlicerAstro-Beta.app/Contents/SlicerAstro-Beta-Extensions/SlicerAstro/lib/Slicer-4.9/qt-loadable-modules/libqSlicerAstroModelingModule.dylib' is not a valid Qt plugin.
  Error(s):
    The file '/Users/vdhulst/Downloads/SlicerAstro-Beta.app/Contents/SlicerAstro-Beta-Extensions/SlicerAstro/lib/Slicer-4.9/qt-loadable-modules/libqSlicerAstroMomentMapsModule.dylib' is not a valid Qt plugin.
  Error(s):
    The file '/Users/vdhulst/Downloads/SlicerAstro-Beta.app/Contents/SlicerAstro-Beta-Extensions/SlicerAstro/lib/Slicer-4.9/qt-loadable-modules/libqSlicerAstroSmoothingModule.dylib' is not a valid Qt plugin.
  Error(s):
    The file '/Users/vdhulst/Downloads/SlicerAstro-Beta.app/Contents/SlicerAstro-Beta-Extensions/SlicerAstro/lib/Slicer-4.9/qt-loadable-modules/libqSlicerAstroVolumeModule.dylib' is not a valid Qt plugin.
Number of registered modules: 27
Number of instantiated modules: 27
dlopen(/Users/vdhulst/Downloads/SlicerAstro-Beta.app/Contents/SlicerAstro-Beta-Extensions/SlicerAstro/lib/Slicer-4.9/qt-loadable-modules/vtkSlicerAstroModelingModuleLogicPython.so, 2): Library not loaded: @rpath/Extensions-26676/SlicerAstro/lib/Slicer-4.9/qt-loadable-modules/libvtkSlicerAstroModelingModuleLogicPythonD.dylib
  Referenced from: /Users/vdhulst/Downloads/SlicerAstro-Beta.app/Contents/SlicerAstro-Beta-Extensions/SlicerAstro/lib/Slicer-4.9/qt-loadable-modules/vtkSlicerAstroModelingModuleLogicPython.so
  Reason: image not found
dlopen(/Users/vdhulst/Downloads/SlicerAstro-Beta.app/Contents/SlicerAstro-Beta-Extensions/SlicerAstro/lib/Slicer-4.9/qt-loadable-modules/vtkSlicerAstroMomentMapsModuleLogicPython.so, 2): Library not loaded: @rpath/Extensions-26676/SlicerAstro/lib/Slicer-4.9/qt-loadable-modules/libvtkSlicerAstroMomentMapsModuleLogicPythonD.dylib
  Referenced from: /Users/vdhulst/Downloads/SlicerAstro-Beta.app/Contents/SlicerAstro-Beta-Extensions/SlicerAstro/lib/Slicer-4.9/qt-loadable-modules/vtkSlicerAstroMomentMapsModuleLogicPython.so
  Reason: image not found
dlopen(/Users/vdhulst/Downloads/SlicerAstro-Beta.app/Contents/SlicerAstro-Beta-Extensions/SlicerAstro/lib/Slicer-4.9/qt-loadable-modules/vtkSlicerAstroSmoothingModuleLogicPython.so, 2): Library not loaded: @rpath/Extensions-26676/SlicerAstro/lib/Slicer-4.9/qt-loadable-modules/libvtkSlicerAstroSmoothingModuleLogicPythonD.dylib
  Referenced from: /Users/vdhulst/Downloads/SlicerAstro-Beta.app/Contents/SlicerAstro-Beta-Extensions/SlicerAstro/lib/Slicer-4.9/qt-loadable-modules/vtkSlicerAstroSmoothingModuleLogicPython.so
  Reason: image not found
dlopen(/Users/vdhulst/Downloads/SlicerAstro-Beta.app/Contents/SlicerAstro-Beta-Extensions/SlicerAstro/lib/Slicer-4.9/qt-loadable-modules/vtkSlicerAstroVolumeModuleLogicPython.so, 2): Library not loaded: @rpath/Extensions-26676/SlicerAstro/lib/Slicer-4.9/qt-loadable-modules/libvtkSlicerAstroVolumeModuleLogicPythonD.dylib
  Referenced from: /Users/vdhulst/Downloads/SlicerAstro-Beta.app/Contents/SlicerAstro-Beta-Extensions/SlicerAstro/lib/Slicer-4.9/qt-loadable-modules/vtkSlicerAstroVolumeModuleLogicPython.so
  Reason: image not found
dlopen(/Users/vdhulst/Downloads/SlicerAstro-Beta.app/Contents/SlicerAstro-Beta-Extensions/SlicerAstro/lib/Slicer-4.9/qt-loadable-modules/vtkSlicerAstroVolumeModuleMRMLPython.so, 2): Library not loaded: @rpath/Extensions-26676/SlicerAstro/lib/Slicer-4.9/qt-loadable-modules/libvtkSlicerAstroVolumeModuleMRMLPythonD.dylib
  Referenced from: /Users/vdhulst/Downloads/SlicerAstro-Beta.app/Contents/SlicerAstro-Beta-Extensions/SlicerAstro/lib/Slicer-4.9/qt-loadable-modules/vtkSlicerAstroVolumeModuleMRMLPython.so
  Reason: image not found
dlopen(/Users/vdhulst/Downloads/SlicerAstro-Beta.app/Contents/SlicerAstro-Beta-Extensions/SlicerAstro/lib/Slicer-4.9/qt-loadable-modules/vtkSlicerAstroVolumeModuleMRMLDisplayableManagerPython.so, 2): Library not loaded: @rpath/Extensions-26676/SlicerAstro/lib/Slicer-4.9/qt-loadable-modules/libvtkSlicerAstroVolumeModuleMRMLDisplayableManagerPythonD.dylib
  Referenced from: /Users/vdhulst/Downloads/SlicerAstro-Beta.app/Contents/SlicerAstro-Beta-Extensions/SlicerAstro/lib/Slicer-4.9/qt-loadable-modules/vtkSlicerAstroVolumeModuleMRMLDisplayableManagerPython.so
  Reason: image not found
dlopen(/Users/vdhulst/Downloads/SlicerAstro-Beta.app/Contents/SlicerAstro-Beta-Extensions/SlicerAstro/lib/Slicer-4.9/qt-loadable-modules/qSlicerAstroVolumeEditorEffectsPythonQt.so, 2): Library not loaded: @rpath/Extensions-26676/SlicerAstro/lib/Slicer-4.9/qt-loadable-modules/libqSlicerAstroVolumeEditorEffects.dylib
  Referenced from: /Users/vdhulst/Downloads/SlicerAstro-Beta.app/Contents/SlicerAstro-Beta-Extensions/SlicerAstro/lib/Slicer-4.9/qt-loadable-modules/qSlicerAstroVolumeEditorEffectsPythonQt.so
  Reason: image not found
dlopen(/Users/vdhulst/Downloads/SlicerAstro-Beta.app/Contents/SlicerAstro-Beta-Extensions/SlicerAstro/lib/Slicer-4.9/qt-loadable-modules/qSlicerAstroVolumeModuleWidgetsPythonQt.so, 2): Library not loaded: @rpath/Extensions-26676/SlicerAstro/lib/Slicer-4.9/qt-loadable-modules/libqSlicerAstroVolumeModuleWidgets.dylib
  Referenced from: /Users/vdhulst/Downloads/SlicerAstro-Beta.app/Contents/SlicerAstro-Beta-Extensions/SlicerAstro/lib/Slicer-4.9/qt-loadable-modules/qSlicerAstroVolumeModuleWidgetsPythonQt.so
  Reason: image not found
Number of loaded modules: 27

**Comment by Punzo** [comment]
here is a link to my config.json file https://www.dropbox.com/s/wnje6ba7yfabrao/config.json?dl=0

**Comment by pieper** [comment]
Hi @Punzo - 

A few questions to clarify...

1. So this worked on the mac build with 4.8 but not with 4.9 nightlies?

2. The loadable module works when correctly outside of the custom slicer but not inside?

3. Do the directory hierarchies (for SlicerAstro) look the same in the custom version of the extension as they do in the installed extension?

4. Is this all possible to reproduce using the nightly builds and nightly extension build?

The custom generator should just be copying files around so maybe something needs to be tweaked to set the paths differently.

Thanks for reporting the issue!

-Steve

**Comment by Punzo** [comment]
Hi Steve, 

1) I never tried to make a custom version of Slicer/SlicerAstro for mac. Only for linux: the linux one worked from 4.7 and they work as well with 4.9 nightlies.

2) yes they work with no problem. If you download the today nightly slicer build and you install SlicerAstro by the extension manager everything is working. The issue is after packing the custom binaries (by running the new custom binaries generated by the customSlicerGenerator extension).

3) yes exactly the same, that's why I think it can be just a path (or mac rpath) issue. Moreover in linux everything work properly.

4) Yes, I tried just today on two different mac laptops (one with Sierra and another with el Capitan). If you'd like to test as well, please just download the today slicer nightly build and SlicerAstro from the extension manager. The config file that I used it is still available at the link above.

5) Yes I definitively think it is a path issue, but I really don't know how they work in mac environment (rpath, etc...).

Thanks for checking !!

**Comment by pieper** [comment]
Okay, yes, I could reproduce this.  It's a pain because the extension files on mac have the rpath hard-coded so they only work in one location relative to the Slicer executable.  And it's not easy to change the rpath because the new path must be shorter or equal to the original path string length.

The issue is that the CustomSlicerGenerator creates a SlicerAstro-Beta-Extensions folder and copies the extensions there, but the hard coded rpath looks in Extensions-<svn-rev-#>.

The easy fix to get things working for your issue with the current Nightly mac build is to move the SlicerAstro folder from SlicerAstro-Beta-Extensions into the Extensions-26680 folder.

Then in two places in SlicerAstro-Beta.app/Contents/lib/Slicer-4.9/qt-scripted-modules/SlicerAstro_BetaCustomizer.py make this edit:
```
      absPath = os.path.join(
                  slicer.app.slicerHome,
                  #"SlicerAstro-Beta"+"-Extensions",
                  "Extensions-26680",
                  relPath)
```

After I do this all the modules load in my SlicerAstro-Beta.app.

We would have to go back and look why there is a SlicerAstro-Beta-Extensions folder at all.  Maybe we should be using the Extensions-<svn-rev-#> directory like regular Slicer does.  If I recall correctly it was meant to avoid accidental name clashes or to allow additional extension installs but this rpath issue make mean that we are forced to use the non-custom path.

**Comment by Punzo** [comment]
Hi @Steve today I was doing a SlicerAstro tutorial and people had the same issue on some linux distro. So I guess the path issue is present also in linux. I'll try the suggested fix and I'll let you know. Most Likely I'll tray again after Slicer VTK9/QT5 release. Thank you very much for checking and the solution. I'll let you know asap. And if it is a general issue also for other extensions, yeah we should fix it.

**Comment by pieper** [comment]
Hi @Punzo sorry you ran into trouble, hope the tutorial went well otherwise.

Jc mentioned the other day that Kitware has some tools for building custom slicer versions and will be releasing them in the near future.  I believe that approach will require setting up build machines for each supported platform, so there will always be some tradeoffs.

**Comment by Punzo** [comment]
HI @pieper no no problem at all. Just a little delay because I had make them download the binaries from the Slicer website and manually configure the settings.

Well, I like your extension because I can use any os (like my laptop) and it doesn't require to set up a proper factory machine (with old os and gcc; and having a machine busy only for the purpose of compiling and packing). However it will be also nice to see what Kitware has.

**Comment by pieper** [comment]
Great - makes sense.  I think the workaround is good simple enough and if it works for you we can adapt the script to work that way.

**Comment by Punzo** [comment]
Hi Steve, I am finalizing the SlicerAstro project and I was planning to create again custom binaries for SlicerAstro (I checked also https://github.com/KitwareMedical/SlicerCustomAppTemplate , but I don't have the time and the machines to build). Instead for your extension with the current nightly of Slicer I had to do a couple of fixes (https://github.com/Punzo/CustomSlicerGenerator/commit/75469547816c7e50eb513683bd600c36aecac813). The problem is that I tried the fix to put the extension libraries in folder of the revision number (and modify the customizer.py), however I get still linking issues:

**Comment by Punzo** [comment]
Error(s):
    Cannot load library /data/users/punzo/SlicerAstro-Stable-02-08-2018-linux-amd64/Extensions-27331/SlicerAstro/lib/Slicer-4.9/qt-loadable-modules/libqSlicerAstroMaskingModule.so: (libqSlicerAstroVolumeModuleWidgets.so: cannot open shared object file: No such file or directory)
  Error(s):
    Cannot load library /data/users/punzo/SlicerAstro-Stable-02-08-2018-linux-amd64/Extensions-27331/SlicerAstro/lib/Slicer-4.9/qt-loadable-modules/libqSlicerAstroModelingModule.so: (libqSlicerAstroVolumeModuleWidgets.so: cannot open shared object file: No such file or directory)
  Error(s):
    Cannot load library /data/users/punzo/SlicerAstro-Stable-02-08-2018-linux-amd64/Extensions-27331/SlicerAstro/lib/Slicer-4.9/qt-loadable-modules/libqSlicerAstroMomentMapsModule.so: (libqSlicerAstroVolumeModuleWidgets.so: cannot open shared object file: No such file or directory)
  Error(s):
    Cannot load library /data/users/punzo/SlicerAstro-Stable-02-08-2018-linux-amd64/Extensions-27331/SlicerAstro/lib/Slicer-4.9/qt-loadable-modules/libqSlicerAstroProfilesModule.so: (libqSlicerAstroVolumeModuleWidgets.so: cannot open shared object file: No such file or directory)
  Error(s):
    Cannot load library /data/users/punzo/SlicerAstro-Stable-02-08-2018-linux-amd64/Extensions-27331/SlicerAstro/lib/Slicer-4.9/qt-loadable-modules/libqSlicerAstroPVDiagramModule.so: (libqSlicerAstroVolumeModuleWidgets.so: cannot open shared object file: No such file or directory)
  Error(s):
    Cannot load library /data/users/punzo/SlicerAstro-Stable-02-08-2018-linux-amd64/Extensions-27331/SlicerAstro/lib/Slicer-4.9/qt-loadable-modules/libqSlicerAstroPVSliceModule.so: (libqSlicerAstroVolumeModuleWidgets.so: cannot open shared object file: No such file or directory)
  Error(s):
    Cannot load library /data/users/punzo/SlicerAstro-Stable-02-08-2018-linux-amd64/Extensions-27331/SlicerAstro/lib/Slicer-4.9/qt-loadable-modules/libqSlicerAstroReprojectModule.so: (libqSlicerAstroVolumeModuleWidgets.so: cannot open shared object file: No such file or directory)
  Error(s):
    Cannot load library /data/users/punzo/SlicerAstro-Stable-02-08-2018-linux-amd64/Extensions-27331/SlicerAstro/lib/Slicer-4.9/qt-loadable-modules/libqSlicerAstroSmoothingModule.so: (libqSlicerAstroVolumeModuleWidgets.so: cannot open shared object file: No such file or directory)
  Error(s):
    Cannot load library /data/users/punzo/SlicerAstro-Stable-02-08-2018-linux-amd64/Extensions-27331/SlicerAstro/lib/Slicer-4.9/qt-loadable-modules/libqSlicerAstroStatisticsModule.so: (libqSlicerAstroVolumeModuleWidgets.so: cannot open shared object file: No such file or directory)
  Error(s):
    Cannot load library /data/users/punzo/SlicerAstro-Stable-02-08-2018-linux-amd64/Extensions-27331/SlicerAstro/lib/Slicer-4.9/qt-loadable-modules/libqSlicerAstroVolumeModule.so: (libqSlicerAstroVolumeModuleWidgets.so: cannot open shared object file: No such file or directory)
When loading module  "AstroMaskingSelfTest" , the dependency "AstroVolume" failed to be loaded.
When loading module  "AstroModelingSelfTest" , the dependency "AstroVolume" failed to be loaded.
When loading module  "AstroMomentMapsSelfTest" , the dependency "AstroVolume" failed to be loaded.
When loading module  "AstroPVDiagramSelfTest" , the dependency "AstroVolume" failed to be loaded.
When loading module  "AstroPVSliceSelfTest" , the dependency "AstroVolume" failed to be loaded.
When loading module  "AstroProfilesSelfTest" , the dependency "AstroVolume" failed to be loaded.
When loading module  "AstroReprojectSelfTest" , the dependency "AstroVolume" failed to be loaded.
When loading module  "AstroSampleData" , the dependency "AstroVolume" failed to be loaded.
When loading module  "AstroSmoothingSelfTest" , the dependency "AstroVolume" failed to be loaded.
When loading module  "AstroStatisticsSelfTest" , the dependency "AstroVolume" failed to be loaded.
When loading module  "AstroVolumeSelfTest" , the dependency "AstroVolume" failed to be loaded.
When loading module  "AstroWelcome" , the dependency "AstroVolume" failed to be loaded.
When loading module  "SlicerAstroDataProbe" , the dependency "AstroVolume" failed to be loaded.

**Comment by Punzo** [comment]
if I copy the extension lib folder in the Slicer tree, everything works(for linux). But it will be nice to fix it. Can be that the issue is that the extension does not have the paths set in the additionalLauncherSettings.ini?

**Comment by Punzo** [comment]
yes the issue was simply that the path are missing in the additionalLauncherSettings.ini. It is not even necessary to apply this fix:
absPath = os.path.join(
                  slicer.app.slicerHome,
                  #"SlicerAstro-Beta"+"-Extensions",
                  "Extensions-26680",
                  relPath)

At least on linux. On Monday I'll try also on mac and I'll let you know

**Comment by Punzo** [comment]
for Mac because of the fixed paths, we have to point to the extension revision. 
I have done the modification to my branch, but I added specific customisation for SlicerAstro, so I'll not do a PR. In case you are interested https://github.com/Punzo/CustomSlicerGenerator. Thanks for the support.

**Comment by pieper** [comment]
Glad you got things working 👍 

I see that some of your commits are specific to SlicerAstro, but some of the others look generic and useful.  If you had time to split out the general purpose updates to the generator into a PR it could be helpful going forward.

**Comment by Punzo** [comment]
Hi Steve, ok I'll do it asap. I had to change the behavior of somethings (for example, I had to remove the automatic restart, because the GUI is not yet opened at that time with the current nightly). However I guess some commit will be good to be reviewed and merged .
